{
 "title": "Resource Recommendations",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(krr_score)/count(krr_score)",
     "legendFormat": "{{strategy_history_duration}}"
    }
   ]
  },
  {
   "title": "Recommended Memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(last_over_time(krr_recommended_requests_memory{exported_namespace=~\"$namespace\"}[12h])) by (kind, name, namespace)",
     "legendFormat": "{{kind}}/{{name}}"
    },
    {
     "expr": "max(last_over_time(krr_recommended_limits_memory{exported_namespace=~\"$namespace\"}[12h])) by (kind, name, namespace)",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  },
  {
   "title": "Recommended CPU",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(last_over_time(krr_recommended_requests_cpu{exported_namespace=~\"$namespace\"}[12h])) by (kind, name, namespace) * 1000",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  },
  {
   "title": "Memory Limits Skew",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(krr_recommended_limits_memory{exported_namespace=~\"$namespace\"} / on(kind, exported_namespace, name, exported_container) krr_allocations_limits_memory{exported_namespace=~\"$namespace\"}) > 0",
     "legendFormat": "{{kind}} - {{name}}:{{exported_container}}"
    },
    {
     "expr": "((krr_recommended_limits_memory{exported_namespace=~\"$namespace\"} / on(kind, exported_namespace, name, exported_container) krr_allocations_limits_memory{exported_namespace=~\"$namespace\"}) - 1) < 0",
     "legendFormat": "{{kind}} - {{name}}:{{exported_container}}"
    }
   ]
  },
  {
   "title": "Memory Requests Skew",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(krr_recommended_requests_memory{exported_namespace=~\"$namespace\"} / on(kind, exported_namespace, name, exported_container) krr_allocations_requests_memory{exported_namespace=~\"$namespace\"}) > 0",
     "legendFormat": "{{kind}} - {{name}}:{{exported_container}}"
    },
    {
     "expr": "((krr_recommended_requests_memory{exported_namespace=~\"$namespace\"} / on(kind, exported_namespace, name, exported_container) krr_allocations_requests_memory{exported_namespace=~\"$namespace\"}) - 1) < 0",
     "legendFormat": "{{kind}} - {{name}}:{{exported_container}}"
    }
   ]
  },
  {
   "title": "CPU Requests Skew",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(krr_recommended_requests_cpu{exported_namespace=~\"$namespace\"} / on(kind, exported_namespace, name, exported_container) krr_allocations_requests_cpu{exported_namespace=~\"$namespace\"}) > 0",
     "legendFormat": "{{kind}} - {{name}}:{{exported_container}}"
    },
    {
     "expr": "((krr_recommended_requests_cpu{exported_namespace=~\"$namespace\"} / on(kind, exported_namespace, name, exported_container) krr_allocations_requests_cpu{exported_namespace=~\"$namespace\"}) - 1) < 0",
     "legendFormat": "{{kind}} - {{name}}:{{exported_container}}"
    }
   ]
  }
 ]
}