{
 "title": "KRR Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=~\"$namespace\"},deployment)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "krr_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Workloads without Mem Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "krr_allocations_limits_memory{namespace!~\"openshift-.*\", namespace=~\"$namespace\",  name=~\"$deployment\"} / 1024 / 1024 ",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "krr_recommended_limits_memory{namespace!~\"openshift-.*\",namespace=~\"$namespace\", name=~\"$deployment\"} /1024 /1024 ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  },
  {
   "title": "Workloads without Memory Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "krr_allocations_requests_memory{namespace!~\"openshift-.*\", namespace=~\"$namespace\",  name=~\"$deployment\"} / 1024 / 1024 ",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "krr_recommended_requests_memory{namespace!~\"openshift-.*\",namespace=~\"$namespace\", name=~\"$deployment\"} /1024 /1024 ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "krr_allocations_requests_cpu{namespace=~\"$namespace\", name=~\"$deployment\"} * 1",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "krr_recommended_requests_cpu{namespace=~\"$namespace\", name=~\"$deployment\"} ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Request - TOP 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "krr_allocations_requests_memory{namespace=~\"$namespace\", name=~\"$deployment\"} / 1024 / 1024",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "krr_recommended_requests_memory{namespace=~\"$namespace\", name=~\"$deployment\"} /1024 /1024 ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Request - TOP 10 by Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(krr_allocations_requests_memory{namespace=~\"$namespace\", name=~\"$deployment\"} / 1024 / 1024) by (namespace)",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "sum(krr_recommended_requests_memory{namespace=~\"$namespace\", name=~\"$deployment\"} /1024 /1024) by (namespace) ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Limit - TOP 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "krr_allocations_limits_memory{namespace=~\"$namespace\", name=~\"$deployment\"} / 1024 / 1024 ",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "krr_recommended_limits_memory{namespace=~\"$namespace\", name=~\"$deployment\"} /1024 /1024 ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Limits - TOP 10 by Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(krr_allocations_limits_memory{namespace=~\"$namespace\", name=~\"$deployment\"} / 1024 / 1024) by (namespace)",
     "legendFormat": "Configured-{{container}}"
    },
    {
     "expr": "sum(krr_recommended_limits_memory{namespace=~\"$namespace\", name=~\"$deployment\"} /1024 /1024) by (namespace) ",
     "legendFormat": "Recommend-{{container}}"
    }
   ]
  }
 ]
}