# Default values for istio peerauthentication
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mtls:
- enabled: false
  name: default
  # https://istio.io/latest/docs/reference/config/security/peer_authentication/#PeerAuthentication-MutualTLS-Mode
  mode: PERMISSIVE
  #selector:
  #  matchLabels:
  #    app: finance
