{{- if .Values.envFrom }}
{{- range $i, $v := .Values.envFrom.secrets }}
{{- if $v.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-deployment.name" $ }}-secret-env-{{ default $i $v.name }}
data:
{{- range $dk, $dv := $v.data }}
  {{ $dk }}: {{ $dv | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
