# Default values for ravendb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

license: license/license.json

tls:
  pfx: certs/tls.pfx
  password: certs/password.txt
  fingerprint: certs/fingerprint.txt
  #trustedCA: certs/trusted-ca.crt
  #trustedFingerprint: certs/trusted-fingerprint.crt

replicaCount: 1

#nodeSelector: {}
#  node-role.kubernetes.io/raven: "true"

storage:
  size: 1Gi
  storageClassName: ""

affinity: {}
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#    - labelSelector:
#        matchExpressions:
#        - key: app.kubernetes.io/instance
#          operator: In
#          values:
#          - ravendb
#      topologyKey: "kubernetes.io/hostname"

image:
  repository: ravendb/ravendb
  tag: "5.1-ubuntu-latest"
  pullPolicy: IfNotPresent

tolerations: []

affinity: {}
