apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ravendb.fullname" . }}-certs
data:
  tls.pfx: {{ .Files.Get .Values.tls.pfx | b64enc }}
  password.txt: {{ .Files.Get .Values.tls.password | b64enc }}
  fingerprint.txt: {{ .Files.Get .Values.tls.fingerprint | b64enc }}
  {{- if .Values.tls.trustedCA }}
  trusted-ca.crt: {{ .Files.Get .Values.tls.trustedCA | b64enc }}
  {{- end }}
  {{- if .Values.tls.trustedFingerprint }}
  trusted-fingerprint.txt: {{ .Files.Get .Values.tls.trustedFingerprint | b64enc }}
  {{- end }}
