apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravendb.fullname" . }}
  labels:
    {{- include "ravendb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http-api
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tcp-server
      port: 38888
      protocol: TCP
      targetPort: 38888
    - name: snmp
      port: 161
      protocol: TCP
      targetPort: 161
  selector:
    {{- include "ravendb.selectorLabels" . | nindent 4 }}
