{{- if .Values.metrics.enabled }}
{{- if has "official" .Values.metrics.exporter_types }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lasa-rabbitmq-monitoring
  namespace: rabbitmq-cluster
spec:
  groups:
  - name: lasa.rules
    rules:
    - alert: QueueHasNoConsumers
      annotations:
        description: |
          Queue {{ "{{ $labels.queue }}" }} from vhost {{ "{{ $labels.vhost }}" }}, pod {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }} has no consumers for 5 minutes.
        summary: |
          Queue {{ "{{ $labels.vhost }}" }}{{ "{{ $labels.queue }}" }} is empty for 5 minutes.
      expr: rabbitmq_queue_consumers == 0
      for: 5m
      labels:
        severity: critical

    - alert: QueueTooBig
      annotations:
        description: |
          Queue {{ "{{ $labels.queue }}" }} from vhost {{ "{{ $labels.vhost }}" }}, pod {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }} is too big: {{ "{{ $value }}" }} > 250
        summary: |
          Queue {{ "{{ $labels.vhost }}" }}{{ "{{ $labels.queue }}" }} is too big: {{ "{{ $value }}" }} > 250
      expr: rabbitmq_queue_messages{queue=~"^(estoque-darkstore-queue|estoque-queue|ml-queue)"} > 250
      for: 5m
      labels:
        severity: critical

    - alert: QueueStuckForTooLong
      annotations:
        description: |
          Queue {{ "{{ $labels.queue }}" }} from vhost {{ "{{ $labels.vhost }}" }}, pod {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }} is stuck for too long: {{ "{{ $value }}" }} minutes.
        summary: |
          Queue {{ "{{ $labels.vhost }}" }}{{ "{{ $labels.queue }}" }} is stuck for {{ "{{ $value }}" }} minutes
      expr: rabbitmq_queue_messages > 0 and changes(rabbitmq_queue_messages{queue=~"^(lojas-darkstore-queue|lojas-queue)$"}[5m]) == 0
      for: 30m
      labels:
        severity: critical
{{- end }}
{{- end }}
