{{- if .Values.metrics.enabled }}
{{- if has "official" .Values.metrics.exporter_types }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lasa-rabbitmq-monitoring
  namespace: rabbitmq-cluster
spec:
  groups:
  - name: lasa.rules
    rules:
    - alert: QueueHasNoConsumers
      annotations:
        description: |
          Queue {{ "{{ $labels.queue }}" }} from vhost {{ "{{ $labels.vhost }}" }}, pod {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }}
          has no consumers for {{ .Values.metrics.rules.queue_has_no_consumers.duration }}
        summary: |
          Queue {{ "{{ $labels.vhost }}" }}{{ "{{ $labels.queue }}" }} is empty for {{ .Values.metrics.rules.queue_has_no_consumers.duration }}.
      expr: rabbitmq_queue_consumers
{{- if .Values.metrics.rules.queue_has_no_consumers.queues -}}
        {queue=~"^({{ .Values.metrics.rules.queue_has_no_consumers.queues | join "|" }})"}
{{- end }} == 0
      for: {{ .Values.metrics.rules.queue_has_no_consumers.duration }}
      labels:
        severity: critical

    - alert: QueueTooBig
      annotations:
        description: |
          Queue {{ "{{ $labels.queue }}" }} from vhost {{ "{{ $labels.vhost }}" }}, pod {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }}
          is too big: {{ "{{ $value }}" }} > {{ .Values.metrics.rules.queue_too_big.total }}
        summary: |
          Queue {{ "{{ $labels.vhost }}" }}{{ "{{ $labels.queue }}" }} is too big: {{ "{{ $value }}" }} > {{ .Values.metrics.rules.queue_too_big.total }}
      expr: rabbitmq_queue_messages
{{- if .Values.metrics.rules.queue_too_big.queues -}}
        {queue=~"^({{ .Values.metrics.rules.queue_too_big.queues | join "|" }})"}
{{- end }} > {{ .Values.metrics.rules.queue_too_big.total }}
      for: {{ .Values.metrics.rules.queue_too_big.duration }}
      labels:
        severity: critical

    - alert: QueueStuckForTooLong
      annotations:
        description: |
          Queue {{ "{{ $labels.queue }}" }} from vhost {{ "{{ $labels.vhost }}" }}, pod {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }} is stuck for too long: {{ "{{ $value }}" }} minutes.
        summary: |
          Queue {{ "{{ $labels.vhost }}" }}{{ "{{ $labels.queue }}" }} is stuck for {{ "{{ $value }}" }} minutes
      expr: rabbitmq_queue_messages > 0 and changes(rabbitmq_queue_messages
{{- if .Values.metrics.rules.queue_stuck_for_too_long.queues -}}
        {queue=~"^({{ .Values.metrics.rules.queue_stuck_for_too_long.queues | join "|" }})"}
{{- end }}[5m]) == 0
      for: {{ .Values.metrics.rules.queue_stuck_for_too_long.duration }}
      labels:
        severity: critical
{{- end }}
{{- end }}
