{{- if .Values.serviceAccount.create }}
{{- if empty .Values.serviceAccount.roleArn }}
{{ fail "Missing required value: serviceAccount.roleArn" }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-credentials-sync.serviceAccountName" . }}
  labels: {{ include "ecr-credentials-sync.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
{{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
