{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-credentials-sync.serviceAccountName" . }}
  labels: {{ include "ecr-credentials-sync.labels" . | nindent 4 }}
  annotations:
{{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
{{- end }}
{{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
