#!/bin/bash

set -e

cd charts
for chart in */; do
    echo Testing $chart
    [ -e "$chart/.test-values.yaml" ] && values="--values $chart/.test-values.yaml" || values=""
    helm template test-$chart $values ./$chart > /dev/null || true
done
