apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openshift-ldap-syncer.fullname" . }}
  labels:
    {{- include "openshift-ldap-syncer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - create
  - update
