kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Values.openshiftAuthenticationNamespace }}
  name: {{ include "openshift-ldap-syncer.fullname" . }}
  labels:
    {{- include "openshift-ldap-syncer.labels" . | nindent 4 }}
data:
  whitelist.txt: |
    {{- range .Values.ldap.whitelist }}
    {{ . }}
    {{- end }}

  blacklist.txt: |
    {{- range .Values.ldap.blacklist }}
    {{ . }}
    {{- end }}
