kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "openshift-ldap-syncer.fullname" . }}
  namespace: {{ .Values.openshiftAuthenticationNamespace }}
  labels:
    {{- include "openshift-ldap-syncer.labels" . | nindent 4 }}
