# Default values for istio peerauthentication
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nodeSelector:
  role: infra

tolerations:
- key: dedicated
  value: infra
  effect: NoSchedule

mtls:
- enabled: false
  name: default
  mode: PERMISSIVE
  #selector:
  #  matchLabels:
  #    app: finance


