{{- if .Values.validatingwebhook.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "tiny-controllers.fullname" . }}
  labels:
    {{- include "tiny-controllers.labels" . | nindent 4 }}
spec:
  secretName: {{ include "tiny-controllers.fullname" . }}
  duration: 87600h
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
  - {{ include "tiny-controllers.fullname" . }}
  - {{ include "tiny-controllers.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "tiny-controllers.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.validatingwebhook.certmanager.clusterissuer }}
{{- end }}
