{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tiny-controllers.fullname" . }}
  labels:
    {{- include "tiny-controllers.labels" . | nindent 4 }}
{{- end }}
rules:
{{- with .Values.controllers }}
{{- if .job.enabled }}
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - update
{{- end }}

{{- if .node.enabled }}
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
{{- end }}

{{- if .volume.enabled }}
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}
