{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tiny-controllers.fullname" . }}
  labels:
    {{- include "tiny-controllers.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tiny-controllers.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tiny-controllers.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
