apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "image-cleanup.fullname" . }}-config
  labels:
    component: imagecleanup
  {{- include "image-cleanup.labels" . | nindent 4 }}
data:
  cronjobs: {{ .Values.config.cronjobs | quote }}