{
 "title": "Istio Cluster Overview",
 "tags": [ "istio" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(istio_requests_total{destination_cluster!=\"unknown\", reporter=\"source\"},destination_service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Total Request Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        istio_requests_total{\n            reporter=\"source\",\n            source_canonical_service=\"istio-ingressgateway\"\n        }[1m]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",source_app=\"istio-ingressgateway\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",source_app=\"istio-ingressgateway\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",source_app=\"istio-ingressgateway\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",source_app=\"istio-ingressgateway\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",source_app=\"istio-ingressgateway\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",source_app=\"istio-ingressgateway\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Node Usage - CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"} * 100 != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Response Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code=~\"^2..\"}[1m])) / sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code!=\"0\"}[1m])) > 0) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "(sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code=~\"^3..\"}[1m])) / sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code!=\"0\"}[1m])) > 0) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "(sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code=~\"^4..\"}[1m])) / sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code!=\"0\"}[1m])) > 0) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "(sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code=~\"^5..\"}[1m])) / sum(rate(istio_requests_total{source_canonical_service=\"istio-ingressgateway\", response_code!=\"0\"}[1m])) > 0) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Request Volume",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n    10,\n    round(\n        sum by (destination_service_name, destination_service_namespace) (\n            rate(\n                istio_requests_total{\n                    destination_service!=\"unknown\",\n                    source_workload=\"istio-ingressgateway\",\n                    destination_service_namespace=~\"$namespace\"\n                }[1m]\n            ) > 0),\n        0.1\n    )\n)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n    10,\n    histogram_quantile(\n        0.99,\n        sum by (le, destination_service_name, destination_service_namespace)(\n            irate(\n                istio_request_duration_milliseconds_bucket{\n                    reporter=\"destination\",\n                    source_workload=\"istio-ingressgateway\",\n                    destination_service_namespace=~\"$namespace\"\n                }[1m]\n            )\n        )\n    ) > 0\n)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Workload CPU Usage (Milicores)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload_type=\"deployment\"}\n) by (workload, namespace))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Workload Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", namespace=~\"$namespace\"}\n  * on(namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload_type=\"deployment\", namespace=~\"$namespace\"}\n) by (workload, namespace))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Service Success Rate (non-5xx responses)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (destination_service_name, destination_service_namespace) (\n    irate(\n        istio_requests_total{\n            reporter=\"source\",\n            source_workload=\"istio-ingressgateway\",\n            response_code!~\"5.*\",\n            destination_service_namespace=~\"$namespace\"\n        }[1m]\n    )\n)\n/\nsum by (destination_service_name, destination_service_namespace) (\n    irate(\n        istio_requests_total{\n            reporter=\"source\",\n            source_workload=\"istio-ingressgateway\",\n            destination_service_namespace=~\"$namespace\"\n        }[1m]\n    ) > 0\n) * 100",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  { "title": "Service Incoming Req/Sec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=~\"$service\"}[1m])) by (source_workload_namespace, source_workload, destination_service_namespace)",
     "legendFormat": "rps: {{source_workload}}"
    }
   ]
  }
 ]
}