{
 "title": "RabbitMQ Queues",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_network_receive_packets_total{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{cluster=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (vhost, queue)",
     "legendFormat": "{{vhost}}@{{queue}}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_channels{cluster=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Messages waiting for Ack",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (vhost, queue)",
     "legendFormat": "{{vhost}}@{{queue}}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_consumers{cluster=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}