# Default values for rabbitmq-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

ingress:
  enabled: false
  className: ""
  hosts:
  - host: rabbitmq.example.com
    path: /
    pathType: Prefix

  tls: []
  #- hosts:
  #  - rabbitmq.example.co
  #  secretName: rabbitmq-cert

  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

service:
  type: ClusterIP
  amqp:
    port: 5672
  management:
    port: 15672

nodePortService:
  enabled: false
  nodePort: 30672

image:
  name: rabbitmq
  tag: 3.8.9-management

affinity: {}
#   nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: role
#          operator: In
#          values:
#          - infra

override: {}

persistence:
  storage: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

tls: {}

tolerations:
  - effect: NoSchedule
    operator: Exists

# Must be string block, not YAML
additionalConfig: ""
#additionalConfig: |-
#   prometheus.return_per_object_metrics = false
#  management.path_prefix = /rabbitmq

# Must be list(string), not YAML
additionalConfigs: []
#additionalConfigs:
#- "prometheus.return_per_object_metrics = false"
#- "management.path_prefix = /rabbitmq"

metrics:
  enabled: true

  rules:
    queue_has_no_consumers:
      queues: []
      duration: 10m
    queue_has_too_many_messages:
    - max: 1000
      duration: 10m
      queues: []
    queue_stuck_for_too_long:
      queues: []
      duration: 30m

  #  For more details about the 'detailed-endpoint,
  #  please refer to the documentation at:
  #  https://www.rabbitmq.com/prometheus.html#detailed-endpoint
  detailed:
    enabled: false
    # params: {}
    params:
      family:
        - queue_coarse_metrics
        - queue_metrics

  ## valid values: official, kbudde
  exporter_types:
  - official
  #- kbudde

  overrides:
    kbudde:
      statefulSet:
        spec:
          template:
            spec:
              containers:
              - name: kbudde-exporter
                env:
                - name: RABBIT_URL
                  value: http://127.0.0.1:15672
                - name: RABBIT_USER
                  valueFrom:
                    secretKeyRef:
                      name: "%RELEASE_NAME%-default-user"
                      key: username
                - name: RABBIT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "%RELEASE_NAME%-default-user"
                      key: password
                - name: OUTPUT_FORMAT
                  value: json
                - name: SKIP_QUEUES
                  value: RPC_.*
                - name: MAX_QUEUES
                  value: "1000"
                image: kbudde/rabbitmq-exporter
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: 9419
                  protocol: TCP
                resources:
                  requests:
                    memory: 128Mi
                    cpu: 100m
                  limits:
                    memory: 128Mi
                    cpu: 100m
