## Must match Charts.yaml:appVersion
eckVersion: 7.10.2

ingress:
  enabled: true
  class: nginx
  clusterIssuer: selfsigned
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

elasticsearch:
  name: es
  ingress:
    url: elastic.example.com
    #enabled: true
    #class: nginx
    #clusterIssuer: selfsigned
    #annotations: {}
  masterNode:
    count: 1
    sysctl:
    - vm.max_map_count=262144
    storage:
      size: 10Gi
      className: ""
    memoryMinGi: 1
    memoryMaxGi: 2
    cpuMin: 1
    cpuMax: 1
    nodeSelector: {}
    tolerations: []
  dataNode:
    count: 1
    sysctl:
    - vm.max_map_count=262144
    storage:
      size: 100Gi
    memoryMinGi: 4
    memoryMaxGi: 4
    cpuMin: 2
    cpuMax: 2
    nodeSelector: {}
    tolerations: []

kibana:
  name: kibana
  count: 1
  xpack:
    security:
      encryptionKey: dGhpcy1pcy1teS1zdXBlci11bnNlY3VyZS1rZXktSS1zaG91bGQtaGF2ZS1jcmVhdGVkLWEtbW9yZS1zZWN1cmUta2V5Cg==
    encryptedSavedObjects:
      encryptionKey: aGVyZS1pLWFtLXVzaW5nLWEtZGVmYXVsdC1pbnNlY3VyZS1rZXktYWdhaW4tLS1zaWdoCg==
  ingress:
    url: kibana.example.com
    #enabled: true
    #class: nginx
    #clusterIssuer: selfsigned
    #annotations: {}
  memoryMinGi: 2
  memoryMaxGi: 2
  cpuMin: 1
  cpuMax: 1
  nodeSelector: {}
  tolerations: []

apmServer:
  name: apm
  count: 1
  ingress:
    url: apm.example.com
    #enabled: true
    #class: nginx
    #clusterIssuer: selfsigned
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-headers: "Accept:,Accept-Encoding,Accept-Language:,Cache-Control,Connection,DNT,Pragma,Host,Referer,Upgrade-Insecure-Requests,User-Agent,elastic-apm-traceparent"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-max-age: "1728000"
  memoryMinGi: 2
  memoryMaxGi: 2
  cpuMin: 1
  cpuMax: 1
  nodeSelector: {}
  tolerations: []
