{{- range $policyName, $policy := .Values.policy }}
{{- with or (get $.Values.policy $policyName) (dict "_" "_") }}
{{- if (default true .enabled) }}
{{- if .nameOverride }}
{{- $policyName = .nameOverride }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ $policyName }}
spec:
  {{- $spec := toYaml (default $.Values.bindingSpec .bindingSpec) }}
  {{- tpl $spec (dict "policyName" $policyName) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
