{{- range $policyName, $policy := .Values.policy }}
{{- with or (get $.Values.policy $policyName) (dict "_" "_") }}
{{- if (default true .enabled) }}
{{- if .nameOverride }}
{{- $policyName = .nameOverride }}
{{- end }}

{{- $validationActions := list "Warn" }}
{{- if .validationActions }}
{{- $validationActions = .validationActions }}
{{- else if $.Values.enforce }}
{{- $validationActions = list "Deny" "Audit" }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ $policyName }}
spec:
  {{- $spec := toYaml (default $.Values.bindingSpec .bindingSpec) }}
  {{- tpl $spec (dict "policyName" $policyName) | nindent 2 }}
  validationActions: {{- toYaml $validationActions | nindent 2 }}
  {{- if .needParams }}
  paramRef:
    name: {{ default "config" $.Values.params.name }}
    #namespace: null
    parameterNotFoundAction: Deny
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
