{{- with or (get .Values.policy "getup-g-101-delete-protection") (dict "_" "_") }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ default "getup-g-101-delete-protection" .nameOverride }}
  labels:
    {{- include "vap.labels" $ | nindent 4 }}
spec:
  failurePolicy: {{ default $.Values.defaultFailurePolicy .failurePolicy }}
  matchConstraints:
    resourceRules:
    - apiGroups:
      - "*"
      apiVersions:
      - "*"
      resources:
      - "*"
      operations:
      - DELETE
  matchConditions:
    - name: hasDeleteLockAnnotation
      expression: "has(oldObject.metadata.annotations) && 'vap.getup.io/delete-lock' in oldObject.metadata.annotations"
  validations:
  - expression: |-
      oldObject.metadata.annotations["vap.getup.io/delete-lock"] != "true"
    message: 'Object locked for deletion by annotation vap.getup.io/delete-lock=true'
    messageExpression: |-
      oldObject.kind + " "
      + (has(oldObject.metadata.namespace) ? (oldObject.metadata.namespace+"/") : "")
      + oldObject.metadata.name
      + " locked for deletion by annotation \"vap.getup.io/delete-lock=true\""
    reason: Invalid
{{- end }}
