{{- with or (get .Values.policy "marvin-m-107-selinux") (dict "_" "_") }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ default "marvin-m-107-selinux" .nameOverride }}
  labels:
    {{- include "vap.labels" $ | nindent 4 }}
spec:
  failurePolicy: {{ default $.Values.defaultFailurePolicy .failurePolicy }}
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - apps
      apiVersions:
      - v1
      resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - batch
      apiVersions:
      - v1
      resources:
      - cronjobs
      - jobs
      operations:
      - CREATE
      - UPDATE
  paramKind:
   apiVersion: getup.io/v1
   kind: VAPConfig
  variables:
  - name: podMeta
    expression: |-
      has(object.spec.containers) ? object.metadata :
        has(object.spec.template) ? object.spec.template.metadata :
        has(object.spec.jobTemplate.spec.template.metadata) ?  object.spec.jobTemplate.spec.template.metadata :
        {}
  - name: podSpec
    expression: |-
      has(object.spec.containers) ? object.spec :
        has(object.spec.template) ? object.spec.template.spec :
        has(object.spec.jobTemplate.spec.template.spec) ?  object.spec.jobTemplate.spec.template.spec :
        {}
  - name: podContainers
    expression: |-
      object.spec.?containers.orValue([]) + object.spec.?initContainers.orValue([]) + object.spec.?ephemeralContainers.orValue([])
  - name: workloadContainers
    expression: |-
      object.spec.?template.spec.containers.orValue([]) + object.spec.?template.spec.initContainers.orValue([])
  - name: cronjobContainers
    expression: |-
      object.spec.?jobTemplate.spec.template.spec.containers.orValue([]) + object.spec.?jobTemplate.spec.template.spec.containers.orValue([])
  - name: allContainers
    expression: |-
      variables.podContainers + variables.workloadContainers + variables.cronjobContainers

  validations:
  - expression: |-
      variables.podSpec.?securityContext.?seLinuxOptions.?type.orValue("") in params.settings.allowedSELinuxTypes
    message: 'Pod with not allowed SELinux type'
    messageExpression: ''
    reason: Invalid
  - expression: |-
      variables.allContainers.all(c, c.?securityContext.?seLinuxOptions.?type.orValue("") in params.settings.allowedSELinuxTypes)
    message: 'Container with not allowed SELinux type'
    messageExpression: ''
    reason: Invalid
  - expression: |-
      variables.podSpec.?securityContext.?seLinuxOptions.?user.orValue("") == ""
    message: 'Pod with forbidden SELinux user'
    messageExpression: ''
    reason: Invalid
  - expression: |-
      variables.allContainers.all(c, c.?securityContext.?seLinuxOptions.?user.orValue("") == "")
    message: 'Container with forbidden SELinux user'
    messageExpression: ''
    reason: Invalid
  - expression: |-
      variables.podSpec.?securityContext.?seLinuxOptions.?role.orValue("") == ""
    message: 'Pod with forbidden SELinux role'
    messageExpression: ''
    reason: Invalid
  - expression: |-
      variables.allContainers.all(c, c.?securityContext.?seLinuxOptions.?role.orValue("") == "")
    message: 'Container with forbidden SELinux role'
    messageExpression: ''
    reason: Invalid

{{- end }}
