{{- with or (get .Values.policy "marvin-m-411-role-binding-referencing-anonymous-or-unauthenticated") (dict "_" "_") }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ default "marvin-m-411-role-binding-referencing-anonymous-or-unauthenticated" .nameOverride }}
  labels:
    {{- include "vap.labels" $ | nindent 4 }}
spec:
  failurePolicy: {{ default $.Values.defaultFailurePolicy .failurePolicy }}
  matchConstraints:
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      resources:
      - rolebindings
      - clusterrolebindings
      operations:
      - CREATE
      - UPDATE
  variables:
  - name: podMeta
    expression: |-
      has(object.spec.containers) ? object.metadata :
        has(object.spec.template) ? object.spec.template.metadata :
        has(object.spec.jobTemplate.spec.template.metadata) ?  object.spec.jobTemplate.spec.template.metadata :
        {}
  - name: podSpec
    expression: |-
      has(object.spec.containers) ? object.spec :
        has(object.spec.template) ? object.spec.template.spec :
        has(object.spec.jobTemplate.spec.template.spec) ?  object.spec.jobTemplate.spec.template.spec :
        {}
  - name: podContainers
    expression: |-
      object.spec.?containers.orValue([]) + object.spec.?initContainers.orValue([]) + object.spec.?ephemeralContainers.orValue([])
  - name: workloadContainers
    expression: |-
      object.spec.?template.spec.containers.orValue([]) + object.spec.?template.spec.initContainers.orValue([])
  - name: cronjobContainers
    expression: |-
      object.spec.?jobTemplate.spec.template.spec.containers.orValue([]) + object.spec.?jobTemplate.spec.template.spec.containers.orValue([])
  - name: allContainers
    expression: |-
      variables.podContainers + variables.workloadContainers + variables.cronjobContainers

  validations:
  - expression: |-
      !has(object.subjects) || object.subjects.all(subject,
        !(subject.kind == "User" && subject.name == "system:anonymous") &&
        !(subject.kind == "Group" && subject.name == "system:unauthenticated")
      )
    message: 'Role Binding referencing anonymous user or unauthenticated group'
    messageExpression: ''
    reason: Invalid

{{- end }}
