{{ with .Values.csiSmb -}}
{{- range . }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: smb.csi.k8s.io
parameters:
  # On Windows, "*.default.svc.cluster.local" could not be recognized by csi-proxy
  #source: "//smb-server.default.svc.cluster.local/share"
  csi.storage.k8s.io/provisioner-secret-name: {{ include "storageclass.fullname" $ }}-{{ .name }}-smbcreds
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ include "storageclass.fullname" $ }}-{{ .name }}-smbcreds
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
{{- range $k, $v := .parameters }}
  {{ $k }}: {{ $v }}
{{- end }}
volumeBindingMode: Immediate
mountOptions:
{{- range .mountOptions }}
- {{ . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storageclass.fullname" $ }}-{{ .name }}-smbcreds
data:
  username: {{ b64enc .username }}
  password: {{ b64enc .password }}
{{- end }}
{{- end }}
