apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "csr-auto-approver.fullname" . }}
  labels:
    {{- include "csr-auto-approver.labels" . | nindent 4 }}
rules:
- apiGroups:
  - CertificateSigningRequest
  verbs:
  - '*'
