kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "openshift-ldap-syncer.fullname" . }}
  labels:
    {{- include "openshift-ldap-syncer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openshift-ldap-syncer.fullname" . }}
    namespace: {{ .Values.openshiftAuthenticationNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openshift-ldap-syncer.fullname" . }}
