{{ if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basic-deployment.name" . }}-config
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
