{{- if .Values.autoscaling.enabled -}}
apiVersion: {{ ternary "autoscaling/v2" "autoscaling/v1" (.Capabilities.APIVersions.Has "autoscaling/v2") }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "basic-deployment.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "basic-deployment.name" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.cpu }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.cpu }}
    {{- end }}
    {{- if .Values.autoscaling.memory }}
    - type: Resource
      resource:
        name: memory
        targetAverageValue: {{ .Values.autoscaling.memory }}
    {{- end }}
{{- end }}
