{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1 #TODO Add Capabilities
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "basic-deployment.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
  {{- if .Values.hpa.statefulset }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
  {{- end }}
    name: {{ include "basic-deployment.name" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.cpu }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.hpa.memory }}
  {{- end }}
{{- end }}