{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "basic-deployment.name" . }}
  labels:
    app: "{{ include "basic-deployment.name" . }}"
    release: {{ .Release.Name | quote }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          serviceName: {{ include "basic-deployment.name" $ }}
          servicePort: http
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- range .Values.ingress.hosts }}
    - {{ .name }}
  {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}