{{ if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-deployment.name" . }}-secret
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}

