{{ if .Values.cronitor.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring-config.fullname" . }}-cronitor
  labels:
    {{- include "monitoring-config.labels" . | nindent 4 }}
    {{- with  .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    release: prometheus-operator
spec:
  groups:
  - name: cronitor.rules
    rules:
    - alert: CronitorWatchdog
      # must have a cycle >4m because this is the default endsAt fiel sent from prometheus to alertmanager
      # otherwise the alert is always updated and never recriated.
      expr: vector(time()) % 270 < 20
      labels:
        severity: none
      annotations:
        description: This is a Watchdog meant to ensure that the entire Alerting pipeline
          is functional, posting continuos alerts to cronitor.io
        summary: Cronitor watchdog alert
{{ end }}
