apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
type: Opaque
data:
  auth: {{ htpasswd .Values.ingress.auth.basic_username .Values.ingress.auth.basic_password | b64enc}}

---
{{ if .Values.loki.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
  namespace: {{ .Values.loki.namespace }}
type: Opaque
data:
  auth: {{ htpasswd .Values.loki.ingress.auth.basic_username .Values.loki.ingress.auth.basic_password | b64enc }}
{{ end }}  


