---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: loki-canary
  name: loki-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-canary
  strategy:
    type: Recreate
  template:
    metadata:
      name: loki-canary
      labels:
        app: loki-canary
    spec:
      containers:
      - args:
        - -addr=loki.{{ .Values.loki.namespace }}.svc:3100
        - -labelname=app
        - -labelvalue=loki-canary
        - -wait=5m0s
        image: grafana/loki-canary:latest
        imagePullPolicy: IfNotPresent
        name: loki-canary
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      {{ if .Values.loki.canary.tolerations }}
      tolerations:
{{ toYaml .Values.loki.canary.tolerations | indent 8 }}
      {{ end }}
      {{ if .Values.loki.canary.node_selector }}
      nodeSelector:
{{ toYaml .Values.loki.canary.node_selector | indent 8 }}
      {{ end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki-canary
  name: loki-canary
spec:
  type: ClusterIP
  selector:
    app: loki-canary
  ports:
  - name: metrics
    protocol: TCP
    port: 3500
    targetPort: 3500

---
apiVersion: {{ .Values.prometheusOperatorCRDsApiVersion }}
kind: ServiceMonitor
metadata:
  labels:
    app: loki-canary
  name: loki-canary
spec:
  endpoints:
  - interval: 30s
    port: metrics
{{ if .Release.namespace }}
  namespaceSelector:
    matchNames:
    - {{ .Release.namespace}}
{{ end }}
  selector:
    matchLabels:
      app: loki-canary
