{{ if .Values.cluster_issuer_selfsigned.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
{{ end }}

{{ if .Values.cluster_issuer_letsencrypt.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-http01
spec:
  acme:
    email: {{ .Values.acme_email }}
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress_class }}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-http01
spec:
  acme:
    email: {{ .Values.acme_email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress_class }}
{{ end }}

{{ if .Values.cluster_issuer_dns01.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns01
spec:
  acme:
    email: {{ .Values.acme_email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
{{ if .Values.cluster_issuer_dns01.aws_zones }}
{{ $zones := split "," .Values.cluster_issuer_dns01.aws_zones | trim " " }}
{{ range $zones  }}
        - {{ . }}
{{ end }}
{{ end }}
      dns01:
        route53:
          region: "{{ .Values.cluster_issuer_dns01.aws_region }}"
          accessKeyID: "{{ .Values.cluster_issuer_dns01.aws_access_key_id }}"
          secretAccessKeySecretRef:
            name: cert-manager-aws-route53-credentials-secret
            key: secret-access-key

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-dns01
spec:
  acme:
    email: {{ .Values.acme_email }}
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      selector:
        dnsZones:
{{ if .Values.cluster_issuer_dns01.aws_zones }}
{{ $zones := split "," .Values.cluster_issuer_dns01.aws_zones | trim " " }}
{{ range $zones }}
        - {{ . }}
{{ end }}
{{ end }}
      dns01:
        route53:
          region: "{{ .Values.cluster_issuer_dns01.aws_region }}"
          accessKeyID: "{{ .Values.cluster_issuer_dns01.aws_access_key_id }}"
          secretAccessKeySecretRef:
            name: cert-manager-aws-route53-credentials-secret
            key: secret-access-key

---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-aws-route53-credentials-secret
type: Opaque
data:
  secret-access-key: "{{ .Values.cluster_issuer_dns01.aws_secret_access_key }}"
{{ end }}
