{
 "title": "Loki-Canary",
 "description": "loki-canary deployed on k8s and with metrics gathered by Prometheus 2.x",
 "tags": [
  "loki",
  "loki-canary"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Loki logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki logs",
   "type": "logs",
   "description": "anything except \"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container=\"loki-canary\"} !=\"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\""
    }
   ]
  },
  { "title": "Missing entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Missing entries rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_canary_missing_entries_total[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Missing entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_canary_missing_entries_total) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket missing entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Websocket missing entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_websocket_missing_entries_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Websocket missing entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_canary_websocket_missing_entries_total",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Websocket reconnects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Websocket reconnects rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_ws_reconnects_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Websocket reconnects",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_canary_ws_reconnects_total",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Out of order entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Out of order entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_out_of_order_entries_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Out of order entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_canary_out_of_order_entries_total",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unexpected entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unexpected entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_unexpected_entries_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Unexpected entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_canary_unexpected_entries_total",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duplicate entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duplicate entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_duplicate_entries_total[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Duplicate entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_canary_duplicate_entries_total",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_entries_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "loki_canary_entries_total", "legendFormat": "{{pod}}" }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response latency",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "loki_canary_response_latency_seconds_bucket"
      }
     ]
    },
    {
     "title": "Response latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "loki_canary_response_latency_seconds_bucket"
      }
     ]
    }
   ]
  }
 ]
}