{
 "title": "Usage ratio",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "up_to_percentage",
    "label": "Up to usage percentage",
    "query": "100,90,80,70,60,50,40,30,20,10,5,2,1"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "podname", "label": "Pod" },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(haproxy_server_up{exported_namespace=~\"^($namespace)$\"}, route)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Status Codes (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(increase(haproxy_server_http_responses_total{exported_namespace=~\"^($namespace)$\", route=~\"^($route)$\"}[1m])) by (code, exported_namespace, route)",
     "legendFormat": "{{ exported_namespace }} / {{ route }} / {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (ratio)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_server_http_responses_total{exported_namespace=~\"^($namespace)$\", route=~\"^($route)$\"}[1m])) by (code, exported_namespace, route)",
     "legendFormat": "{{ exported_namespace }} / {{ route }} / {{ code }}"
    }
   ]
  },
  {
   "title": "CPU Usage (ratio)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(\n      container_cpu_usage_seconds_total{namespace=~\"^($namespace)$\", image!=\"\", container_name!=\"POD\", pod_name=~\".*[[podname]].*\"}[5m]\n    )\n  ) by (\n      pod_name, container_name, namespace\n  )\n  /\n  sum(\n    container_spec_cpu_quota{namespace=~\"^($namespace)$\", image!=\"\", container_name!=\"POD\", pod_name=~\".*[[podname]].*\"}\n    /\n    container_spec_cpu_period{namespace=~\"^($namespace)$\", image!=\"\", container_name!=\"POD\", pod_name=~\".*[[podname]].*\"}\n  ) by (\n    pod_name, container_name, namespace\n  )\n) < (\n  $up_to_percentage / 100\n)",
     "legendFormat": "{{ namespace }} / {{ pod_name }} / {{ container_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage (ratio)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\", container_name!=\"POD\", namespace=~\"^($namespace)$\", pod_name=~\".*[[podname]].*\"}\n/\non(name, namespace, pod_name, container_name) container_spec_memory_limit_bytes{name!=\"\", container_name!=\"POD\", pod_name=~\".*[[podname]].*\"}\n<\n($up_to_percentage / 100)",
     "legendFormat": "{{ namespace }} / {{pod_name}} / {{ container_name }} "
    }
   ]
  },
  {
   "title": "Storage Usage (ratio)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Usage" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"^($namespace)$\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"^($namespace)$\"}",
     "legendFormat": "{{ namespace }} / {{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}