apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twemproxy.fullname" . }}
  labels:
    {{- include "twemproxy.labels" . | nindent 4 }}
data:
  nutcracker.yml: |-
    {{- range $name, $config := $.Values.redisInstances }}
    {{ $name }}:
      {{- omit $config "stats_port" | toYaml | nindent 6 }}
    {{- end }}
