apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twemproxy.fullname" . }}
  labels:
    {{- include "twemproxy.labels" . | nindent 4 }}
data:
  {{- range $name, $config := $.Values.redisInstances }}
  {{ $name }}: |-
    {{ $name }}:
      {{- omit $config "stats_port" | toYaml | nindent 6 }}
  {{- end }}
