apiVersion: v1
kind: Service
metadata:
  name: {{ include "twemproxy.fullname" . }}
  labels:
    {{- include "twemproxy.labels" . | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    {{- range $name, $config := $.Values.redisInstances }}
    {{- $port := last (regexSplit ":" $config.listen -1) }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
    {{- if .Values.metrics.enabled}}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "twemproxy.selectorLabels" . | nindent 4 }}
