{
 "title": "Kong Services Monitoring",
 "description": "Kong Services",
 "tags": [
  "kong",
  "services"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(exported_service)" }
  ]
 },
 "panels": [
  { "title": "Total Requests by Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kong_http_status)" }
   ]
  },
  {
   "title": "Current Requests - 2xx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_http_status{code=~\"2[0-9][0-9]\"})"
    }
   ]
  },
  {
   "title": "Current Requests - 3xx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_http_status{code=~\"3[0-9][0-9]\"})",
     "legendFormat": "sdas"
    }
   ]
  },
  {
   "title": "Current Requests - 4xx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_http_status{code=~\"4[0-9][0-9]\"})",
     "legendFormat": "sdas"
    }
   ]
  },
  {
   "title": "Current Requests - 5xx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_http_status{code=~\"5[0-9][0-9]\"})",
     "legendFormat": "sdas"
    }
   ]
  },
  {
   "title": "DB reachability",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_datastore_reachable)*100/count(kong_datastore_reachable)"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "repeat": "api",
   "yaxes": [
    { "format": "decbytes", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "kong_bandwidth{type=\"egress\"} * -1",
     "legendFormat": "Downstream"
    },
    {
     "expr": "kong_bandwidth{type=\"ingress\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  { "title": "HTTP 5xx Errors by Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTT 5xx Errors by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "repeat": "api",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kong_http_status{exported_service=~\"$service\", code=~\"^5[0-9][0-9]\"}) by (code, exported_service)",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  { "title": "Latency by Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request Latency by Service (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "api",
   "yaxes": [
    { "format": "ms", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_latency_count{exported_service=~\"$service\", type=\"request\"}[5m])) by (exported_service)",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  }
 ]
}