{
 "title": "Kong (official)",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong-plugin-prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(kong_http_status,exported_service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests per second (RPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "DB reachability",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kong_datastore_reachable)*100/count(kong_datastore_reachable)"
    }
   ]
  },
  {
   "title": "RPS per service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Egress per service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth{type=\"egress\", service =~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingress per service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth{type=\"ingress\", service =~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"kong\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"kong\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"kong\", service =~ \"$service\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Request Time across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"request\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"request\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Time per service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"request\", service =~ \"$service\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Upstream time across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"upstream\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Upstream Time across per service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$service\"}[1m])) by (le,service))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$service\"}[1m])) by (le,service))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$service\"}[1m])) by (le,service))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Nginx connection state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_nginx_http_current_connections{state=~\"activ|reading|writing|waiting\"}[1m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_nginx_http_current_connections{state=\"total\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_nginx_http_current_connections{state=\"handled\"})",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kong_nginx_http_current_connections{state=\"accepted\"})",
     "legendFormat": "Accepted"
    }
   ]
  }
 ]
}