---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}
spec:
  version: {{ .Values.eckVersion }}
  http:
    tls:
      selfSignedCertificate:
        disabled: {{ .Values.elasticsearch.tls.disabled }}
  nodeSets:
  - name: master
    secureSettings:
    - secretName: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}-secure-settings
    count: {{ .Values.elasticsearch.masterNode.count }}
    config:
{{- if .Values.eckVersion | semverCompare "~6" }}
      node.master: true
{{- else }}
      node.roles:
      - master
{{- end }}
{{- $configs := mergeOverwrite .Values.elasticsearch.config .Values.elasticsearch.masterNode.config }}
{{- toYaml $configs | nindent 6 }}
    podTemplate:
      spec:
        nodeSelector: {{- toYaml .Values.elasticsearch.masterNode.nodeSelector | nindent 10 }}
        tolerations: {{- toYaml .Values.elasticsearch.masterNode.tolerations | nindent 10 }}
{{- with .Values.elasticsearch.masterNode.sysctl }}
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
  {{- range . }}
          - {{ . }}
  {{- end }}
{{- end }}
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 10m
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms{{ default (printf "%dg" (sub .Values.elasticsearch.masterNode.memoryMaxGi 1)) .Values.elasticsearch.masterNode.memoryXms }} -Xmx{{ default (printf "%dg" (sub .Values.elasticsearch.masterNode.memoryMaxGi 1)) .Values.elasticsearch.masterNode.memoryXmx }}
{{- if .Values.elasticsearch.masterNode.env }}
          {{- toYaml .Values.elasticsearch.masterNode.env | nindent 10 }}
{{- end }}
          resources:
            requests:
              memory: {{ .Values.elasticsearch.masterNode.memoryMinGi }}Gi
              cpu: {{ .Values.elasticsearch.masterNode.cpuMin }}
            limits:
              memory: {{ .Values.elasticsearch.masterNode.memoryMaxGi }}Gi
              cpu: {{ .Values.elasticsearch.masterNode.cpuMax }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.masterNode.storage.size }}
{{- if .Values.elasticsearch.masterNode.storage.className }}
        storageClassName: {{ .Values.elasticsearch.masterNode.storage.className }}
{{- end }}
  - name: data
    count: {{ .Values.elasticsearch.dataNode.count }}
    secureSettings:
    - secretName: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}-secure-settings
    config:
{{- if .Values.eckVersion | semverCompare "~6" }}
      node.data: true
      node.ingest: true
      node.ml: true
{{- else }}
      node.roles:
      - data
      - ingest
      - ml
      - transform
{{- end }}
{{- $configs := mergeOverwrite .Values.elasticsearch.config .Values.elasticsearch.dataNode.config }}
{{- toYaml $configs | nindent 6 }}
    podTemplate:
      spec:
        nodeSelector: {{- toYaml .Values.elasticsearch.dataNode.nodeSelector | nindent 10 }}
        tolerations: {{- toYaml .Values.elasticsearch.dataNode.tolerations | nindent 10 }}
{{- with .Values.elasticsearch.dataNode.sysctl }}
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
  {{- range . }}
          - {{ . }}
  {{- end }}
{{- end }}
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 10m
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms{{ default (printf "%dg" (sub .Values.elasticsearch.dataNode.memoryMaxGi 1)) .Values.elasticsearch.dataNode.memoryXms }} -Xmx{{ default (printf "%dg" (sub .Values.elasticsearch.dataNode.memoryMaxGi 1)) .Values.elasticsearch.dataNode.memoryXmx }}
{{- if .Values.elasticsearch.dataNode.env }}
          {{- toYaml .Values.elasticsearch.dataNode.env | nindent 10 }}
{{- end }}
          resources:
            requests:
              memory: {{ .Values.elasticsearch.dataNode.memoryMinGi }}Gi
              cpu: {{ .Values.elasticsearch.dataNode.cpuMin }}
            limits:
              memory: {{ .Values.elasticsearch.dataNode.memoryMaxGi }}Gi
              cpu: {{ .Values.elasticsearch.dataNode.cpuMax }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.dataNode.storage.size }}
{{- if .Values.elasticsearch.dataNode.storage.className }}
        storageClassName: {{ .Values.elasticsearch.dataNode.storage.className }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}-secure-settings
type: Opaque
data:
{{- range $k, $v := .Values.elasticsearch.secureSettings }}
  {{ $k }}: {{ $v | toString | b64enc }}
{{- end }}

{{- $ingress := mergeOverwrite .Values.ingress .Values.elasticsearch.ingress }}
{{- with $ingress }}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- with .class }}
    kubernetes.io/ingress.class: {{ . }}
{{- end }}
{{- with .clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
{{- end }}
  name: {{ $.Release.Name }}-{{ $.Values.elasticsearch.name }}
spec:
  rules:
  - host: {{ .url }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ $.Values.elasticsearch.name }}-es-http
          servicePort: 9200
        path: /
  tls:
  - hosts:
    - {{ .url }}
    secretName: {{ $.Release.Name }}-{{ $.Values.elasticsearch.name }}-ingress-cert
{{- end }}
{{- end }}
