---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}-{{ .Values.kibana.name }}
spec:
  version: {{ .Values.eckVersion }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}
  secureSettings:
  - secretName: {{ .Release.Name }}-{{ .Values.kibana.name }}-secret-settings
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: {{ .Values.kibana.memoryMinGi }}Gi
            cpu: {{ .Values.kibana.cpuMin }}
          limits:
            memory: {{ .Values.kibana.memoryMaxGi }}Gi
            cpu: {{ .Values.kibana.cpuMax }}
      nodeSelector: {{- toYaml .Values.kibana.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.kibana.tolerations | nindent 8 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.kibana.name }}-secret-settings
type: Opaque
data:
  xpack.security.encryptionKey: {{ .Values.kibana.xpack.security.encryptionKey | b64enc }}
{{- if .Values.eckVersion | semverCompare "~7" }}
  xpack.encryptedSavedObjects.encryptionKey: {{ .Values.kibana.xpack.encryptedSavedObjects.encryptionKey | b64enc }}
{{- end }}

---
{{- $ingress := mergeOverwrite .Values.ingress .Values.kibana.ingress }}
{{- with $ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- with .class }}
    kubernetes.io/ingress.class: {{ . }}
{{- end }}
{{- with .clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
{{- end }}
  name: {{ $.Release.Name }}-{{ $.Values.kibana.name }}
spec:
  rules:
  - host: {{ .url }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ $.Values.kibana.name }}-kb-http
          servicePort: 5601
        path: /
  tls:
  - hosts:
    - {{ .url }}
    secretName: {{ $.Release.Name }}-{{ $.Values.kibana.name }}-ingress-cert
{{- end }}
{{- end }}
