---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}-{{ .Values.kibana.name }}
spec:
  version: {{ .Values.eckVersion }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}
  secureSettings:
  - secretName: {{ .Release.Name }}-{{ .Values.kibana.name }}-secure-settings
  http:
    tls:
      selfSignedCertificate:
        disabled: {{ .Values.kibana.tls.disabled }}
  config: {{- toYaml .Values.kibana.config | nindent 4 }}
  podTemplate:
    spec:
      containers:
      - name: kibana
        env: {{- toYaml .Values.kibana.env | nindent 10 }}
        resources:
          requests:
            memory: {{ .Values.kibana.memoryMinGi }}Gi
            cpu: {{ .Values.kibana.cpuMin }}
          limits:
            memory: {{ .Values.kibana.memoryMaxGi }}Gi
            cpu: {{ .Values.kibana.cpuMax }}
      nodeSelector: {{- toYaml .Values.kibana.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.kibana.tolerations | nindent 8 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.kibana.name }}-secure-settings
type: Opaque
data:
{{- range $k, $v := .Values.kibana.secureSettings }}
  {{- if and ($.Values.eckVersion | semverCompare "<7") }}
    {{- if not (eq $k "xpack.encryptedSavedObjects.encryptionKey") }}
  {{ $k }}: {{ $v | toString | b64enc }}
    {{- end }}
  {{- else }}
  {{ $k }}: {{ $v | toString | b64enc }}
  {{- end }}
{{- end }}

---
{{- $ingress := mergeOverwrite .Values.ingress .Values.kibana.ingress }}
{{- with $ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- with .class }}
    kubernetes.io/ingress.class: {{ . }}
{{- end }}
{{- with .clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
{{- end }}
  name: {{ $.Release.Name }}-{{ $.Values.kibana.name }}
spec:
  rules:
  - host: {{ .url }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ $.Values.kibana.name }}-kb-http
          servicePort: 5601
        path: /
  tls:
  - hosts:
    - {{ .url }}
    secretName: {{ $.Release.Name }}-{{ $.Values.kibana.name }}-ingress-cert
{{- end }}
{{- end }}
