---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: {{ .Release.Name }}-{{ .Values.apmServer.name }}
spec:
  version: {{ .Values.eckVersion }}
  count: {{ .Values.apmServer.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}
{{- if .Values.eckVersion | semverCompare "~7" }}
  kibanaRef:
    name: {{ .Release.Name }}-{{ .Values.kibana.name }}
{{- end }}
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          requests:
            memory: {{ .Values.apmServer.memoryMinGi }}Gi
            cpu: {{ .Values.apmServer.cpuMin }}
          limits:
            memory: {{ .Values.apmServer.memoryMaxGi }}Gi
            cpu: {{ .Values.apmServer.cpuMax }}
      nodeSelector: {{- toYaml .Values.apmServer.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.apmServer.tolerations | nindent 8 }}

---
{{- $ingress := mergeOverwrite .Values.ingress .Values.apmServer.ingress }}
{{- with $ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- with .class }}
    kubernetes.io/ingress.class: {{ . }}
{{- end }}
{{- with .clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
{{- end }}
  name: {{ $.Release.Name }}-{{ default $.Values.apmServer.name }}
spec:
  rules:
  - host: {{ .url }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ $.Values.apmServer.name }}-apm-http
          servicePort: 8200
        path: /
  tls:
  - hosts:
    - {{ .url }}
    secretName: {{ $.Release.Name }}-{{ $.Values.apmServer.name }}-ingress-cert
{{- end }}
{{- end }}
