---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: {{ .Release.Name }}-{{ .Values.apmServer.name }}
spec:
  version: {{ .Values.eckVersion }}
  count: {{ .Values.apmServer.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}-{{ .Values.elasticsearch.name }}
{{- if .Values.eckVersion | semverCompare "~7" }}
  kibanaRef:
    name: {{ .Release.Name }}-{{ .Values.kibana.name }}
{{- end }}
  secureSettings:
  - secretName: {{ .Release.Name }}-{{ .Values.apmServer.name }}-secure-settings
  http:
    tls:
      selfSignedCertificate:
        disabled: {{ .Values.apmServer.tls.disabled }}
  config: {{- toYaml .Values.apmServer.config | nindent 4 }}
  podTemplate:
    spec:
      containers:
      - name: apm-server
        env: {{- toYaml .Values.apmServer.env | nindent 10 }}
        resources:
          requests:
            memory: {{ .Values.apmServer.memoryMinGi }}Gi
            cpu: {{ .Values.apmServer.cpuMin }}
          limits:
            memory: {{ .Values.apmServer.memoryMaxGi }}Gi
            cpu: {{ .Values.apmServer.cpuMax }}
      nodeSelector: {{- toYaml .Values.apmServer.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.apmServer.tolerations | nindent 8 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.apmServer.name }}-secure-settings
type: Opaque
data:
{{- range $k, $v := .Values.apmServer.secureSettings }}
  {{ $k }}: {{ $v | toString | b64enc }}
{{- end }}
---
{{- $ingress := mergeOverwrite .Values.ingress .Values.apmServer.ingress }}
{{- with $ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- with .class }}
    kubernetes.io/ingress.class: {{ . }}
{{- end }}
{{- with .clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
{{- end }}
  name: {{ $.Release.Name }}-{{ default $.Values.apmServer.name }}
spec:
  rules:
  - host: {{ .url }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ $.Values.apmServer.name }}-apm-http
          servicePort: 8200
        path: /
  tls:
  - hosts:
    - {{ .url }}
    secretName: {{ $.Release.Name }}-{{ $.Values.apmServer.name }}-ingress-cert
{{- end }}
{{- end }}
