#environment: PROD
#what: world
#size: 1024

templates: []
## Multline-string template
#- |-
#  hello: {{ .Values.what }}

## Object template
#- apiVersion: v1
#  kind: ConfigMap
#  metadata:
#    labels:
#      app: example
#    name: config
#    namespace: default
#  data:
#    config:
#      ENVIRONMENT: '{{ .Values.environment | default "DEVELOPMENT" }}'
#      USERNAME: admin
#      SIZE: "{{ .Values.size }}"
