extraLabels: {}
# app: monitoring-config
# x: y

cronitor:
  # url: "https://cronitor.link/XXXXXX/run" ## creates a hook pod to hit the first time in the monitor endpoint
  prometheusRules:
    enabled: false

rabbitmq:
  prometheusRules:
    enabled: false

loki:
  prometheusRules:
    enabled: true
    lokiJobName: loki-headless
    canary:
      enabled: false
  ingress:
    basicAuth:
      enabled: false
      secretName: loki-basic-auth
      secretNamespace: logging
      username: "logging"
      password: "logging"

prometheusStack:
  prometheusRules:
    enabled: true
    rulesDefaults:
      NodeDiskRunningFull:
        expr: "(node:node_filesystem_usage: > 0.70) and (predict_linear(node:node_filesystem_avail:[6h], 3600 * 24) < 0)"
        for: 1h
      NodeDiskAlmostFull:
        expr: "node:node_filesystem_avail: * 100 < 15"
        for: 1h
  ingress:
    basicAuth:
      enabled: false
      secretName: monitoring-basic-auth
      secretNamespace: monitoring
      username: "monitoring"
      password: "monitoring"
