cronitor:
  prometheusRules:
    enabled: false

velero:
  prometheusRules:
    enabled: true

rabbitmq:
  prometheusRules:
    enabled: false

loki:
  prometheusRules:
    enabled: true
    canary:
      enabled: false
  ingress:
    basicAuth:
      enabled: false
      secretName: loki-basic-auth
      secretNamespace: logging
      username: "logging"
      password: "logging"

prometheusStack:
  prometheusRules:
    enabled: true
  ingress:
    basicAuth:
      enabled: false
      secretName: monitoring-basic-auth
      secretNamespace: monitoring
      username: "monitoring"
      password: "monitoring"
