serviceAccount:
  create: true
  ## roleArn is Required if create=true
  roleArn: "" ## Example: arn:aws:iam::000000000000:role/ECRReadRole
  annotations: {}
  name: ""

secret:
  # secret name to create for credentials
  name: ecr-credentials
  # labelselector for namespaces where to create credential secrets
  # valid for "kubectl -l"'s format
  namespaceSelector: ecr-credentials

awsAccountId: "000000000000"

# https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html
ecr:
  ## ecr.region is Required
  region: "" ## one of registries keys
  registrySuffix:
    af-south-1: dkr.ecr.af-south-1.amazonaws.com
    ap-east-1: dkr.ecr.ap-east-1.amazonaws.com
    ap-northeast-1: dkr.ecr.ap-northeast-1.amazonaws.com
    ap-northeast-2: dkr.ecr.ap-northeast-2.amazonaws.com
    ap-northeast-3: dkr.ecr.ap-northeast-3.amazonaws.com
    ap-south-1: dkr.ecr.ap-south-1.amazonaws.com
    ap-southeast-1: dkr.ecr.ap-southeast-1.amazonaws.com
    ap-southeast-2: dkr.ecr.ap-southeast-2.amazonaws.com
    ca-central-1: dkr.ecr.ca-central-1.amazonaws.com
    cn-north-1: dkr.ecr.cn-north-1.amazonaws.com.cn
    cn-northwest-1: dkr.ecr.cn-northwest-1.amazonaws.com.cn
    eu-central-1: dkr.ecr.eu-central-1.amazonaws.com
    eu-north-1: dkr.ecr.eu-north-1.amazonaws.com
    eu-south-1: dkr.ecr.eu-south-1.amazonaws.com
    eu-west-1: dkr.ecr.eu-west-1.amazonaws.com
    eu-west-2: dkr.ecr.eu-west-2.amazonaws.com
    eu-west-3: dkr.ecr.eu-west-3.amazonaws.com
    me-south-1: dkr.ecr.me-south-1.amazonaws.com
    sa-east-1: dkr.ecr.sa-east-1.amazonaws.com
    us-east-1: dkr.ecr.us-east-1.amazonaws.com
    us-east-2: dkr.ecr.us-east-2.amazonaws.com
    us-gov-east-1: dkr.ecr.us-gov-east-1.amazonaws.com
    us-gov-west-1: dkr.ecr.us-gov-west-1.amazonaws.com
    us-west-1: dkr.ecr.us-west-1.amazonaws.com
    us-west-2: dkr.ecr.us-west-2.amazonaws.com

schedule: "0 */5 * * *"

nodeSelector: {}

tolerations: []

affinity: {}
