{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "x509-exporter-discovery.fullname" . }}
  labels:
    {{- include "x509-exporter-discovery.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
{{- end }}
