apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "x509-exporter-discovery.fullname" . }}
  labels:
    {{- include "x509-exporter-discovery.labels" . | nindent 4 }}
data:
{{- if .Values.excludes }}
  excludes: |-
{{- range .Values.excludes }}
    {{ . }}
{{- end }}
{{- end }}
