apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krr2prom.fullname" . }}
  labels:
    {{- include "krr2prom.labels" . | nindent 4 }}
    app.kubernetes.io/name: krr2prom
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "krr2prom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: krr2prom
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "krr2prom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: krr2prom
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "krr2prom.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- if .Values.config.maxWorkers }}
          - name: MAX_WORKERS
            value: {{ .Values.config.maxWorkers | quote }}
          {{- end }}
          {{- if .Values.config.prometheusURL }}
          - name: PROMETHEUS_URL
            value: {{ .Values.config.prometheusURL | quote }}
          {{- end }}
          {{- if .Values.config.scanFrequency }}
          - name: SCAN_FREQUENCY
            value: {{ .Values.config.scanFrequency | quote }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - emptyDir: {}
        name: data
