apiVersion: v1
kind: Service
metadata:
  name: {{ include "krr2prom.fullname" . }}
  labels:
    {{- include "krr2prom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "krr2prom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: krr2prom
