{{- if .Values.kibana.enabled }}
---
apiVersion: v1
kind: Secret
data: 
  xpack.security.encryptionKey: {{ .Values.kibana.xpack.security.encryptionKey }}
  xpack.encryptedSavedObjects.encryptionKey: {{ .Values.kibana.xpack.encryptedSavedObjects.encryptionKey }}
metadata:
  name: kibana-secret-settings
#  namespace: {{ .Release.namespace }}
type: Opaque

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-{{ .Values.elasticsearch.name }}
#  namespace: {{ .Release.namespace }}
spec:
  version: {{ .Values.eckVersion }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: es-{{ .Values.elasticsearch.name }}
#    namespace: {{ .Release.namespace }}
  secureSettings:
  - secretName: kibana-secret-settings
  http:
    service:
      {{- with .Values.kibana.service.annotations }}
      metadata:
        annotations:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      spec:
      {{- with .Values.kibana.service.type }}
        type: {{ toYaml . }}
      {{- end }}
#    tls:
#      certificate:
#        secretName: kb-{{ .Values.elasticsearch.name }}-ingress-cert
  podTemplate:
    metadata:
      labels:
      {{- with .Values.kibana.pod.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        app: kibana
    spec:
      containers:
      - name: kibana
        {{- with .Values.kibana.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.kibana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kibana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}

---
{{- if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- with .Values.kibana.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: kibana-http
#  namespace: {{ .Release.namespace }}
spec:
  rules:
  - host: {{ .Values.kibana.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: kb-{{ .Values.elasticsearch.name }}-kb-http
          servicePort: 5601
        path: /
  tls:
  - hosts:
    - {{ .Values.kibana.ingress.url }}
    secretName: kb-{{ .Values.elasticsearch.name }}-ingress-cert
  {{- end }}

