{{- if .Values.metrics.enabled -}}
{{ if has "official" .Values.metrics.exporter_types }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}-official
spec:
  endpoints:
  - port: prometheus
    scheme: http
    interval: 30s
    scrapeTimeout: 15s
  - port: prometheus-tls
    scheme: https
    interval: 30s
    scrapeTimeout: 15s
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true
{{- end }}

{{ if has "kbudde" .Values.metrics.exporter_types }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}-kbudde
spec:
  endpoints:
  - port: prometheus
    scheme: http
    interval: 30s
    scrapeTimeout: 15s
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true
{{- end }}

{{- end }}
