apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  affinity:
    {{- toYaml .Values.affinity | nindent 4 }}
  image: {{ .Values.image.name }}:{{ .Values.image.tag }}
{{- $override := deepCopy .Values.override }}
{{- if and (has "official" .Values.metrics.exporter_types) .Values.metrics.overrides.official }}
{{- $override := deepCopy .Values.metrics.overrides.official | merge $override }}
{{- end }}
{{- if and (has "kbudde" .Values.metrics.exporter_types) .Values.metrics.overrides.kbudde }}
{{- $override := deepCopy .Values.metrics.overrides.kbudde | merge $override }}
{{- end }}
  override:
    {{- toYaml $override | replace "%RELEASE_NAME%" .Release.Name | nindent 4 }}
  persistence:
    {{- toYaml .Values.persistence | nindent 4 }}
{{- if or .Values.additionalConfig .Values.additionalConfigs }}
  rabbitmq:
    additionalConfig: |
      {{- .Values.additionalConfig | nindent 6 }}
{{- range .Values.additionalConfigs }}
      {{ . }}
{{- end }}
{{- end }}
  replicas: {{ .Values.replicas }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  service:
    type: ClusterIP
  terminationGracePeriodSeconds: 300
  tls:
    {{- toYaml .Values.tls | nindent 4 }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
