{{ with .Values.ingress }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:
    {{ toYaml .annotations | nindent 4 }}
  name: {{ include "rabbitmq-cluster.fullname" $ }}
  labels:
    {{- include "rabbitmq-cluster.labels" $ | nindent 4 }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .className }}
  {{- end }}
  rules:
  {{- range .hosts }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "rabbitmq-cluster.fullname" $ }}
            port:
              number: {{ $.Values.service.management.port }}
          {{- else }}
          serviceName: {{ include "rabbitmq-cluster.fullname" $ }}
          servicePort: {{ $.Values.service.management.port }}
          {{- end }}
        path: {{ .path }}
        {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: {{ .pathType }}
        {{- end }}
  {{- end }}
  {{- with .tls }}
  tls:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
