{{- if .Values.metrics.enabled -}}
{{ if has "official" .Values.metrics.exporter_types }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}-official
spec:
  endpoints:
  - port: prometheus
    scheme: http
    interval: 30s
    scrapeTimeout: 15s
  - port: prometheus-tls
    scheme: https
    interval: 30s
    scrapeTimeout: 15s
    tlsConfig:
      insecureSkipVerify: true
  {{- if .Values.metrics.detailed.enabled }}
  - port: prometheus
    scheme: http
    path: /metrics/detailed
    params:
      {{- with .Values.metrics.detailed.params }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    interval: 15s
    scrapeTimeout: 14s
  - port: prometheus-tls
    scheme: https
    path: /metrics/detailed
    params:
      {{- with .Values.metrics.detailed.params }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    interval: 15s
    scrapeTimeout: 14s
    tlsConfig:
      insecureSkipVerify: true
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true
{{- end }}

{{ if has "kbudde" .Values.metrics.exporter_types }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}-kbudde
spec:
  endpoints:
  - port: prometheus
    scheme: http
    interval: 30s
    scrapeTimeout: 15s
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true
{{- end }}

{{- end }}
