{{- range $k, $t := (.Values.templates | default list) }}
{{-   if ne (kindOf $t) "string" }}
{{-     $t = toYaml $t }}
{{-   end }}
---
# .Values.templates[{{$k}}]
{{    tpl $t $ }}
{{- end }}

{{- range $k, $t := .Values }}
{{-   if hasPrefix "template-" $k }}
{{-     if ne (kindOf $t) "string" }}
{{        $t = toYaml $t }}
{{-     end }}
---
# .Values.{{$k}}
{{      tpl $t $ }}
{{-   end }}
{{- end }}
